module MemPalaceAgentFrameworkExt

using MemPalace
using AgentFramework
using Dates: DateTime, now, UTC

using MemPalace: Palace, Drawer, SearchHit, SearchResults, mine_text!,
                 search as mp_search, embed, build_closet_lines,
                 _pack_and_store_closets!, AbstractMemPalaceEmbedder,
                 AbstractPalaceBackend, InMemoryPalaceBackend,
                 DeterministicEmbedder, add_drawer!, query_drawers,
                 delete_drawers!, count_drawers

using AgentFramework: AbstractMemoryStore, MemoryRecord, MemorySearchResult,
                      BaseContextProvider, AgentSession, SessionContext,
                      Message, ROLE_USER, ROLE_ASSISTANT, extend_messages!

import AgentFramework: add_memories!, search_memories, get_memories,
                       clear_memories!, before_run!, after_run!

# ── MemPalaceMemoryStore <: AbstractMemoryStore ──────────────────────────────

"""
    MemPalaceMemoryStore(; palace = Palace())

Adapter that exposes a [`MemPalace.Palace`](@ref) as an
`AgentFramework.AbstractMemoryStore`. Plug it into the existing
`MemoryContextProvider` to give any agent a MemPalace-backed memory:

```julia
using AgentFramework, MemPalace
store = MemPalaceMemoryStore()
provider = MemoryContextProvider(store = store)
agent = Agent(client = client, context_providers = [provider])
```

Each `MemoryRecord` is stored as a single drawer; `record.scope` maps to
the drawer's `wing`, `record.kind` (e.g. `:episodic`) to the `room`.
This keeps the AF-flavoured "scope/kind" model intact while still letting
direct MemPalace users address wings/rooms freely.
"""
mutable struct MemPalaceMemoryStore <: AbstractMemoryStore
    palace::Palace
    # Reverse-index from MemoryRecord.id => drawer.id, since drawers get
    # autogenerated ids when constructed via the high-level API.
    record_to_drawer::Dict{String, String}
end

function MemPalaceMemoryStore(;
        palace::Palace = Palace(),
)
    return MemPalaceMemoryStore(palace, Dict{String, String}())
end

function Base.show(io::IO, s::MemPalaceMemoryStore)
    print(io, "MemPalaceMemoryStore(",
              count_drawers(s.palace.backend), " drawers)")
end

function _record_to_drawer(s::MemPalaceMemoryStore, rec::MemoryRecord)::Drawer
    text = isempty(strip(rec.content)) ? "" : String(rec.content)
    role = String(rec.role)
    body = isempty(text) ? "" : string(role, ": ", text)
    md = Dict{String, Any}(
        "record_id"    => rec.id,
        "kind"         => String(rec.kind),
        "role"         => role,
        "session_id"   => something(rec.session_id, ""),
        "author_name"  => something(rec.author_name, ""),
        "message_id"   => something(rec.message_id, ""),
    )
    for (k, v) in rec.metadata
        md[String(k)] = v
    end
    return Drawer(
        text = body,
        wing = String(rec.scope),
        room = String(rec.kind),
        source_file = "",
        chunk_index = 0,
        created_at = rec.created_at,
        metadata = md,
    )
end

function _drawer_to_record(d::Drawer)::MemoryRecord
    md = d.metadata
    rid = haskey(md, "record_id") ? String(md["record_id"]) : d.id
    role = haskey(md, "role") && !isempty(String(md["role"])) ?
           Symbol(String(md["role"])) : ROLE_USER
    kind = haskey(md, "kind") && !isempty(String(md["kind"])) ?
           Symbol(String(md["kind"])) : Symbol(d.room)
    session_id = haskey(md, "session_id") && !isempty(String(md["session_id"])) ?
                 String(md["session_id"]) : nothing
    author_name = haskey(md, "author_name") && !isempty(String(md["author_name"])) ?
                  String(md["author_name"]) : nothing
    message_id = haskey(md, "message_id") && !isempty(String(md["message_id"])) ?
                 String(md["message_id"]) : nothing
    # Strip the leading "role: " prefix we added on ingest.
    text = d.text
    prefix = string(role, ": ")
    if startswith(text, prefix)
        text = text[nextind(text, length(prefix)):end]
    end
    return MemoryRecord(
        id = rid, scope = d.wing, kind = kind, role = role,
        content = text, created_at = d.created_at,
        session_id = session_id, author_name = author_name,
        message_id = message_id,
        metadata = Dict{String, Any}(
            k => v for (k, v) in md
            if !(k in ("record_id", "kind", "role", "session_id",
                       "author_name", "message_id"))
        ),
    )
end

function add_memories!(store::MemPalaceMemoryStore, records::AbstractVector{MemoryRecord})
    for rec in records
        d = _record_to_drawer(store, rec)
        emb = embed(store.palace.embedder, d.text)
        add_drawer!(store.palace.backend, d, emb)
        store.record_to_drawer[rec.id] = d.id
    end
    return store
end

function search_memories(store::MemPalaceMemoryStore, query::AbstractString;
                          scope::Union{Nothing, AbstractString} = nothing,
                          limit::Int = 5)::Vector{MemorySearchResult}
    qemb = embed(store.palace.embedder, query)
    pairs = query_drawers(store.palace.backend, qemb;
                           wing = scope, n_results = limit)
    out = MemorySearchResult[]
    for (d, dist) in pairs
        push!(out, MemorySearchResult(
            record = _drawer_to_record(d),
            score = max(0.0, 1.0 - dist),
        ))
    end
    return out
end

function get_memories(store::MemPalaceMemoryStore;
                       scope::Union{Nothing, AbstractString} = nothing,
                       limit::Union{Nothing, Int} = nothing)::Vector{MemoryRecord}
    out = MemoryRecord[]
    for (_, d) in store.palace.backend.drawers
        scope !== nothing && d.wing != scope && continue
        push!(out, _drawer_to_record(d))
    end
    sort!(out; by = r -> r.created_at)
    if limit !== nothing && length(out) > limit
        return out[(end - limit + 1):end]
    end
    return out
end

function clear_memories!(store::MemPalaceMemoryStore;
                          scope::Union{Nothing, AbstractString} = nothing)
    if scope === nothing
        MemPalace.clear!(store.palace.backend)
    else
        ids = String[]
        for (id, d) in store.palace.backend.drawers
            d.wing == String(scope) && push!(ids, id)
        end
        delete_drawers!(store.palace.backend; ids = ids)
    end
    return store
end

# ── MemPalaceContextProvider <: BaseContextProvider ──────────────────────────

const _DEFAULT_PROMPT =
    "## MemPalace context\nConsider the following verbatim memories when answering the user:"

"""
    MemPalaceContextProvider(palace; wing=nothing, room=nothing,
                              n_results=5, context_prompt=...,
                              wing_metadata_key="memory_scope",
                              room_metadata_key="memory_kind",
                              store_roles=[ROLE_USER, ROLE_ASSISTANT],
                              store=true)

Native context provider for MemPalace that exposes the palace's
wing/room scoping directly. On `before_run!` it runs a hybrid search
scoped by wing (and optionally room) and injects the top hits as
verbatim user-message context. On `after_run!` it ingests the user
input + assistant reply as new drawers (when `store=true`).

Wing/room can be set per-call via `session.metadata` keys (default
`"memory_scope"` and `"memory_kind"`). If unset, the constructor's
`wing` / `room` are used. If those are also `nothing`, falls back to
`session.user_id` / `session.thread_id` / `session.id` for the wing —
matching the behaviour of `AgentFramework.MemoryContextProvider`.
"""
mutable struct MemPalaceContextProvider <: BaseContextProvider
    palace::Palace
    wing::Union{Nothing, String}
    room::Union{Nothing, String}
    n_results::Int
    context_prompt::String
    source_id::String
    wing_metadata_key::String
    room_metadata_key::String
    store_roles::Vector{Symbol}
    store::Bool
end

function MemPalaceContextProvider(palace::Palace;
        wing::Union{Nothing, AbstractString} = nothing,
        room::Union{Nothing, AbstractString} = nothing,
        n_results::Int = 5,
        context_prompt::AbstractString = _DEFAULT_PROMPT,
        source_id::AbstractString = "mempalace",
        wing_metadata_key::AbstractString = "memory_scope",
        room_metadata_key::AbstractString = "memory_kind",
        store_roles::Vector{Symbol} = [ROLE_USER, ROLE_ASSISTANT],
        store::Bool = true,
)
    return MemPalaceContextProvider(
        palace,
        wing === nothing ? nothing : String(wing),
        room === nothing ? nothing : String(room),
        n_results,
        String(context_prompt),
        String(source_id),
        String(wing_metadata_key),
        String(room_metadata_key),
        store_roles,
        store,
    )
end

function Base.show(io::IO, p::MemPalaceContextProvider)
    print(io, "MemPalaceContextProvider(wing=", repr(p.wing),
              ", room=", repr(p.room),
              ", n_results=", p.n_results, ")")
end

function _resolve_wing(p::MemPalaceContextProvider, session::AgentSession)::Union{Nothing, String}
    p.wing !== nothing && return p.wing
    if haskey(session.metadata, p.wing_metadata_key)
        v = session.metadata[p.wing_metadata_key]
        v !== nothing && !isempty(strip(string(v))) && return strip(string(v))
    end
    session.user_id !== nothing && return session.user_id
    session.thread_id !== nothing && return session.thread_id
    return session.id
end

function _resolve_room(p::MemPalaceContextProvider, session::AgentSession)::Union{Nothing, String}
    p.room !== nothing && return p.room
    if haskey(session.metadata, p.room_metadata_key)
        v = session.metadata[p.room_metadata_key]
        v !== nothing && !isempty(strip(string(v))) && return strip(string(v))
    end
    return nothing
end

function _format_hits(hits::SearchResults, prompt::AbstractString)::String
    body = IOBuffer()
    println(body, prompt)
    for (i, h) in enumerate(hits)
        println(body, "[", i, "] (score=", round(h.score; digits=3), ")")
        for line in split(h.drawer.text, '\n')
            println(body, "    ", line)
        end
    end
    return String(take!(body))
end

function _latest_user_query(ctx::SessionContext)::Union{Nothing, String}
    for msg in Iterators.reverse(ctx.input_messages)
        text = strip(msg.text)
        isempty(text) && continue
        return String(text)
    end
    return nothing
end

function before_run!(p::MemPalaceContextProvider, agent,
                     session::AgentSession, ctx::SessionContext,
                     state::Dict{String, Any})
    query = _latest_user_query(ctx)
    query === nothing && return nothing
    state["last_query"] = query

    wing = _resolve_wing(p, session)
    room = _resolve_room(p, session)
    hits = mp_search(p.palace, query;
                     wing = wing, room = room,
                     n_results = p.n_results)
    state["last_result_count"] = length(hits)
    isempty(hits) && return nothing

    text = _format_hits(hits, p.context_prompt)
    extend_messages!(ctx, p, [Message(ROLE_USER, text)])
    return nothing
end

function after_run!(p::MemPalaceContextProvider, agent,
                    session::AgentSession, ctx::SessionContext,
                    state::Dict{String, Any})
    p.store || return nothing
    wing = something(_resolve_wing(p, session), "default")
    room = something(_resolve_room(p, session), "general")
    allowed = Set(p.store_roles)

    n = 0
    for msg in ctx.input_messages
        text = strip(msg.text)
        isempty(text) && continue
        msg.role in allowed || continue
        mine_text!(p.palace, string(msg.role, ": ", text);
                    wing = wing, room = room, build_closets = false)
        n += 1
    end
    if ctx.response !== nothing && hasproperty(ctx.response, :messages)
        for msg in ctx.response.messages
            text = strip(msg.text)
            isempty(text) && continue
            msg.role in allowed || continue
            mine_text!(p.palace, string(msg.role, ": ", text);
                        wing = wing, room = room, build_closets = false)
            n += 1
        end
    end
    state["stored_count"] = get(state, "stored_count", 0) + n
    return nothing
end

# Re-export for callers that only `using MemPalace`.
export MemPalaceMemoryStore, MemPalaceContextProvider

end # module MemPalaceAgentFrameworkExt
